# Semana 2: Clase 2

## Las tuplas no se pueden modificar, consume pocos recursos

In [16]:
a=(1,2,2,3,4,5,7)

In [17]:
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [20]:
a =a.__add__(tuple('1')).__add__(tuple('a'))

In [21]:
a

(1, 2, 2, 3, 4, 5, 7, '1', 'a')

## Listas por comprensión, en python se manejan arreglo-listas

In [23]:
lc = []

### Se considera primero los elementos base y luego los filtros

In [40]:
lc =[x for x in range(20) if x%2 !=0]

In [37]:
lc

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

#### Cuando se usan () se crea un genexpr que es lazzy

In [53]:
lc =(x for x in range(20) if x%2 !=0)
lc

<generator object <genexpr> at 0x7f437c12c0f8>

In [54]:
for x in lc:
    print(x)

1
3
5
7
9
11
13
15
17
19


In [55]:
nombre = "Uriel"
direccion = "reforma"
telefono = "55555"
print("El nombre:"+nombre+", Direccion: "+direccion+", Telefono:"+telefono)

El nombre:Uriel, Direccion: reforma, Telefono:55555


In [56]:
print("El nombre:{0}, Direccion: {1} ,Teléfono:{2} ".format(nombre,direccion,telefono))

El nombre:Uriel, Direccion: reforma ,Teléfono:55555 


#### El format sirve para modificar el formato, se puede truncar

In [71]:
'{:1.10f}'.format(3.14159264)

'3.1415926400'

In [63]:
'{:8d}'.format(42)

'      42'

## ITERTOOLS
#### Iteradores especiales

In [73]:
import itertools

### dir() muestra las librerías cargadas y las variables

In [75]:
dir()

['In',
 'Out',
 '_',
 '_10',
 '_11',
 '_12',
 '_14',
 '_15',
 '_17',
 '_18',
 '_19',
 '_21',
 '_28',
 '_32',
 '_37',
 '_4',
 '_5',
 '_52',
 '_53',
 '_57',
 '_58',
 '_59',
 '_61',
 '_62',
 '_63',
 '_64',
 '_65',
 '_66',
 '_69',
 '_70',
 '_71',
 '_74',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i55',
 '_i56',
 '_i57',
 '_i58',
 '_i59',
 '_i6',
 '_i60',
 '_i61',
 '_i62',
 '_i63',
 '_i64',
 '_i65',
 '_i66',
 '_i67',
 '_i68',
 '_i69',
 '_i7',
 '_i70',
 '_i7

####  '__builtin__', '__builtins__', contienen las librerías básicas

In [76]:
import itertools as it

In [77]:
dir()

['In',
 'Out',
 '_',
 '_10',
 '_11',
 '_12',
 '_14',
 '_15',
 '_17',
 '_18',
 '_19',
 '_21',
 '_28',
 '_32',
 '_37',
 '_4',
 '_5',
 '_52',
 '_53',
 '_57',
 '_58',
 '_59',
 '_61',
 '_62',
 '_63',
 '_64',
 '_65',
 '_66',
 '_69',
 '_70',
 '_71',
 '_74',
 '_75',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i55',
 '_i56',
 '_i57',
 '_i58',
 '_i59',
 '_i6',
 '_i60',
 '_i61',
 '_i62',
 '_i63',
 '_i64',
 '_i65',
 '_i66',
 '_i67',
 '_i68',
 '_i69',
 '_i7',
 '_i70

# Heap y Stack en memoria, son para todos los procesos
##  - Stack: lo que se declaró en el programa de tamaño fijo, inclusive un ciclo que tiene un tamaño definido (   for (int i =0;i<10)   )
##  - Heap: Todo lo que se declara que no tiene un tamaño fija: lista, for elemento in lista, malloc, calloc, TODOS los iteradores viven en Heap

## Itertools reserva un espacio en el Heap solo para Python (lo cual no se permite normalmente), por eso ya no necesita control de memoria y usa la evaluación perezosa (lazzy).
## Los beneficios son en tiempo de ejecución, pero tiene un impacto en recursos.

In [11]:
#import itertools as it
from itertools import *

### Iteradores infinitos.
#### Un iterador es un conjunto de elementos que tinen un indicador(índice)
#### Los iteradores indefinidos, infinitos: count(), cycle(), repeat(), no deben ir solos

# Cycle(): Puede iterar sobre una lista muy larga y está optimizado para esas aplicaciones.

In [12]:
contador = 0

for item in cycle([1,2,3]):
    if contador ==5:
        break
        
    contador +=1
    
    print(item)

1
2
3
1
2


# islice()
### Es de evaluación lazzy, hace el trabajo de un range() pero optimizado
### Normalmente coun() va acompañado de islice

In [21]:
iterador = islice(count(),5,10)

In [22]:
iterador

# Pickle
### Archivo de tipo binario serializable 
### Se puede guardar cualqueir contenido de una variable sin pérdida de datos ya que es al mas bajo nivel.

In [28]:
import pickle

In [29]:
favorite_color = {"lion":"yellow","kitty":"fred"}

### Se guarda la variable en el archivo "Save.p" "wb"-> write binary

In [37]:
pickle.dump(favorite_color, open("Save.p","wb"))

### Se recupera la variable del archivo "Save.p" "rb"-> read binary

In [38]:
favorite_color = pickle.load(open("Save.p","rb"))

In [39]:
favorite_color

{'lion': 'yellow', 'kitty': 'fred'}

# Numpy (Numerical Python), arreglos optimizados
# Se basan en numpy:
### scipy
### pandas
### dataframe(spark)

In [1]:
from numpy import *

In [2]:
arreglo_1 = zeros(5)

print(arreglo_1)

[ 0.  0.  0.  0.  0.]


In [3]:
arreglo_1 = ones(5)
print(arreglo_1)

[ 1.  1.  1.  1.  1.]


In [5]:
print(pi)

3.14159265359


In [7]:
print(e)

2.71828182846


In [8]:
arreglo_1 = zeros((5,5))

In [9]:
print(arreglo_1)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


# Semana 2: Clase 4

In [10]:
arreglo_1 = ones((4,6))

In [11]:
print(arreglo_1)

[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


In [12]:
import sys

In [13]:
sys.path

['',
 '/opt/cloudera/parcels/Anaconda-5.0.1/lib/python27.zip',
 '/opt/cloudera/parcels/Anaconda-5.0.1/lib/python2.7',
 '/opt/cloudera/parcels/Anaconda-5.0.1/lib/python2.7/plat-linux2',
 '/opt/cloudera/parcels/Anaconda-5.0.1/lib/python2.7/lib-tk',
 '/opt/cloudera/parcels/Anaconda-5.0.1/lib/python2.7/lib-old',
 '/opt/cloudera/parcels/Anaconda-5.0.1/lib/python2.7/lib-dynload',
 '/opt/cloudera/parcels/Anaconda-5.0.1/lib/python2.7/site-packages',
 '/opt/cloudera/parcels/Anaconda-5.0.1/lib/python2.7/site-packages/IPython/extensions',
 '/home/cloudera/.ipython']

In [16]:
arreglo_3 = array([1.,2.,3.,4.,5.])
print arreglo_3

[ 1.  2.  3.  4.  5.]


In [17]:
type(arreglo_3)

numpy.ndarray

In [18]:
arreglo_3 + arreglo_3

array([  2.,   4.,   6.,   8.,  10.])

#### El arreglo en numpy realiza operaciones matemáticas y no concatena

In [21]:
ones(4)*4

array([ 4.,  4.,  4.,  4.])

In [43]:
## ndarray es una forma de declarar una matriz
matrix([[1,2,3],
       [4,5,6]])


matrix([[1, 2, 3],
        [4, 5, 6]])

In [90]:
ndarray(buffer=array([10, 0, 0, 10]), shape=(2,2))

array([[  4.94065646e-323,   0.00000000e+000],
       [  0.00000000e+000,   4.94065646e-323]])

In [54]:
ones(4).mean()

1.0

In [55]:
ones(4).sum()

4.0

In [74]:
ndarray(shape=(3,), dtype=float,buffer = array( [1,2,3]))

array([  4.94065646e-324,   9.88131292e-324,   1.48219694e-323])

## Pandas permite usar dataframe en python, los dataframe son super tablas ya que tienen atributos adicionales, los cuales se ejecutan de manera recurrente y paralelo pero no distribuido; los dataframe que se pueden distribuir son los de spark. DataFrame no tiene funciones map, por lo cual se puden usar udf, el rdd si tiene.

In [76]:
import pandas as pd

In [77]:
dataframe = pd.read_csv("ejercicio_5.txt")

In [78]:
dataframe

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0   1987     10          14          3      741         730      912   
1   1987     10          15          4      729         730      903   
2   1987     10          17          6      741         730      918   
3   1987     10          18          7      729         730      847   
4   1987     10          19          1      749         730      922   
5   1987     10          21          3      728         730      848   
6   1987     10          22          4      728         730      852   
7   1987     10          23          5      731         730      902   
8   1987     10          24          6      744         730      908   
9   1987     10          25          7      729         730      851   
10  1987     10          26          1      735         730      904   
11  1987     10          28          3      741         725      919   
12  1987     10          29          4      742         725      906   
13  1987     10          31          6      726         725      848   
14  1987     10           1          4      936         915     1035   
15  1987     10           2          5      918         915     1017   
16  1987     10           3          6      928         915     1037   
17  1987     10           4          7      914         915     1003   
18  1987     10           5          1     1042         915     1129   
19  1987     10           6          2      934         915     1024   
20  1987     10           7          3      946         915     1037   
21  1987     10           8          4      932         915     1033   
22  1987     10           9          5      947         915     1036   
23  1987     10          10          6      915         915     1022   
24  2008     12          13          6     1531        1522     1822   
25  2008     12          13          6     1910        1910     2017   
26  2008     12          13          6     1441        1445     1604   
27  2008     12          13          6      921         830     1112   
28  2008     12          13          6     1435        1440     1701   
29  2008     12          13          6     1750        1755     2010   
30  2008     12          13          6      706         710      850   
31  2008     12          13          6     1552        1520     1735   
32  2008     12          13          6     1250        1220     1617   
33  2008     12          13          6     1033        1041     1255   
34  2008     12          13          6      840         843     1025   
35  2008     12          13          6      810         815     1504   
36  2008     12          13          6      547         545      646   
37  2008     12          13          6      848         850     1024   
38  2008     12          13          6      936         936     1114   
39  2008     12          13          6      657         600      904   
40  2008     12          13          6     1007         847     1149   
41  2008     12          13          6      638         640      808   
42  2008     12          13          6      756         800     1032   
43  2008     12          13          6      612         615      923   
44  2008     12          13          6      749         750      901   
45  2008     12          13          6     1002         959     1204   
46  2008     12          13          6      834         835     1021   
47  2008     12          13          6      655         700      856   
48  2008     12          13          6     1251        1240     1446   
49  2008     12          13          6     1110        1103     1413   

    CRSArrTime UniqueCarrier  FlightNum         ...         TaxiIn  TaxiOut  \
0          849            PS       1451         ...            NaN      NaN   
1          849            PS       1451         ...            NaN      NaN   
2          849            PS       1451         ...            NaN      NaN   
3          849 

In [82]:
type(dataframe)

pandas.core.frame.DataFrame

In [80]:
dataframe

## Para poder utilizar paquetes que operan únicamente en concurrente y paralelo pero no en distribuido se deben importar dentro de la definición de la función y ser llamadas por la función lambda:


In [91]:
# def funcion(x):
#    import pandas as pd

#spark_rdd.map(lambda x:funcion(x))

In [92]:
dataframe.describe()

Year      Month  DayofMonth  DayOfWeek     DepTime   CRSDepTime  \
count    50.000000  50.000000   50.000000  50.000000    50.00000    50.000000   
mean   1997.920000  11.040000   14.100000   5.180000   929.72000   916.520000   
std      10.598113   1.009344    6.624783   1.560874   297.51632   295.946716   
min    1987.000000  10.000000    1.000000   1.000000   547.00000   545.000000   
25%    1987.000000  10.000000   13.000000   4.250000   732.00000   730.000000   
50%    2008.000000  12.000000   13.000000   6.000000   844.00000   839.000000   
75%    2008.000000  12.000000   14.750000   6.000000   988.25000   915.000000   
max    2008.000000  12.000000   31.000000   7.000000  1910.00000  1910.000000   

           ArrTime   CRSArrTime    FlightNum  ActualElapsedTime  \
count    50.000000    50.000000    50.000000          50.000000   
mean   1110.120000  1080.420000  1542.360000          94.800000   
std     323.327889   335.883975    88.897272          36.642788   
min     646.000000   650.000000  1451.000000          43.000000   
25%     904.000000   849.000000  1451.000000          69.750000   
50%    1023.000000  1001.000000  1612.000000          89.500000   
75%    1144.000000  1095.750000  1627.750000         111.000000   
max    2017.000000  2016.000000  1641.000000         234.000000   

           ...           Distance     TaxiIn    TaxiOut  Cancelled  \
count      ...          50.000000  26.000000  26.000000       50.0   
mean       ...         457.460000  10.653846  21.615385        0.0   
std        ...         286.311961   6.305187  11.235931        0.0   
min        ...         151.000000   4.000000   7.000000        0.0   
25%        ...         226.000000   6.250000  13.000000        0.0   
50%        ...         447.000000   8.000000  19.000000        0.0   
75%        ...         528.500000  13.750000  25.500000        0.0   
max        ...        1900.000000  24.000000  46.000000        0.0   

       CancellationCode  Diverted  CarrierDelay  WeatherDelay   NASDelay  \
count               0.0      50.0      8.000000      8.000000   8.000000   
mean                NaN       0.0      6.875000      7.125000  12.500000   
std                 NaN       0.0     17.860071     20.152543   7.982123   
min                 NaN       0.0      0.000000      0.000000   0.000000   
25%                 NaN       0.0      0.000000      0.000000   9.750000   
50%                 NaN       0.0      0.000000      0.000000  15.500000   
75%                 NaN       0.0      1.500000      0.000000  18.250000   
max                 NaN       0.0     51.000000     57.000000  19.000000   

       SecurityDelay  
count            8.0  
mean             0.0  
std              0.0  
min              0.0  
25%              0.0  
50%              0.0  
75%              0.0  
max              0.0  

[8 rows x 24 columns]

In [93]:
# un dataframe de pandas les asigna un tipo de dato a las columnas

In [94]:
dir(dataframe)

['ActualElapsedTime',
 'AirTime',
 'ArrDelay',
 'ArrTime',
 'CRSArrTime',
 'CRSDepTime',
 'CRSElapsedTime',
 'CancellationCode',
 'Cancelled',
 'CarrierDelay',
 'DayOfWeek',
 'DayofMonth',
 'DepDelay',
 'DepTime',
 'Dest',
 'Distance',
 'Diverted',
 'FlightNum',
 'Month',
 'NASDelay',
 'Origin',
 'SecurityDelay',
 'T',
 'TailNum',
 'TaxiIn',
 'TaxiOut',
 'UniqueCarrier',
 'WeatherDelay',
 'Year',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__i

In [97]:
#Registros, Columnas
dataframe.shape

(50, 29)

In [98]:
type(dataframe.shape)

tuple

In [99]:
dataframe.Year

0     1987
1     1987
2     1987
3     1987
4     1987
5     1987
6     1987
7     1987
8     1987
9     1987
10    1987
11    1987
12    1987
13    1987
14    1987
15    1987
16    1987
17    1987
18    1987
19    1987
20    1987
21    1987
22    1987
23    1987
24    2008
25    2008
26    2008
27    2008
28    2008
29    2008
30    2008
31    2008
32    2008
33    2008
34    2008
35    2008
36    2008
37    2008
38    2008
39    2008
40    2008
41    2008
42    2008
43    2008
44    2008
45    2008
46    2008
47    2008
48    2008
49    2008
Name: Year, dtype: int64

In [100]:
dataframe["Year"]

0     1987
1     1987
2     1987
3     1987
4     1987
5     1987
6     1987
7     1987
8     1987
9     1987
10    1987
11    1987
12    1987
13    1987
14    1987
15    1987
16    1987
17    1987
18    1987
19    1987
20    1987
21    1987
22    1987
23    1987
24    2008
25    2008
26    2008
27    2008
28    2008
29    2008
30    2008
31    2008
32    2008
33    2008
34    2008
35    2008
36    2008
37    2008
38    2008
39    2008
40    2008
41    2008
42    2008
43    2008
44    2008
45    2008
46    2008
47    2008
48    2008
49    2008
Name: Year, dtype: int64

In [110]:
# Los valores de pandas se pueden colocar en float32 o float64

In [111]:
dataframe["Year"].sum()

99896L

In [112]:
dataframe["Year"].mean()

1997.92

In [123]:
#Filtrado por filas
#loc
#iloc
#dataframe.iloc(0)
#dataframe.iloc[-1]
dataframe.iloc[0]

Year                  1987
Month                   10
DayofMonth              14
DayOfWeek                3
DepTime                741
CRSDepTime             730
ArrTime                912
CRSArrTime             849
UniqueCarrier           PS
FlightNum             1451
TailNum                NaN
ActualElapsedTime       91
CRSElapsedTime          79
AirTime                NaN
ArrDelay                23
DepDelay                11
Origin                 SAN
Dest                   SFO
Distance               447
TaxiIn                 NaN
TaxiOut                NaN
Cancelled                0
CancellationCode       NaN
Diverted                 0
CarrierDelay           NaN
WeatherDelay           NaN
NASDelay               NaN
SecurityDelay          NaN
LateAircraftDelay      NA 
Name: 0, dtype: object

In [124]:
# no permite dataframe.loc[-1]
dataframe.loc[0]

Year                  1987
Month                   10
DayofMonth              14
DayOfWeek                3
DepTime                741
CRSDepTime             730
ArrTime                912
CRSArrTime             849
UniqueCarrier           PS
FlightNum             1451
TailNum                NaN
ActualElapsedTime       91
CRSElapsedTime          79
AirTime                NaN
ArrDelay                23
DepDelay                11
Origin                 SAN
Dest                   SFO
Distance               447
TaxiIn                 NaN
TaxiOut                NaN
Cancelled                0
CancellationCode       NaN
Diverted                 0
CarrierDelay           NaN
WeatherDelay           NaN
NASDelay               NaN
SecurityDelay          NaN
LateAircraftDelay      NA 
Name: 0, dtype: object

In [127]:
# Filtrados por observacón
dataframe.iloc[2:5]

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
2  1987     10          17          6      741         730      918   
3  1987     10          18          7      729         730      847   
4  1987     10          19          1      749         730      922   

   CRSArrTime UniqueCarrier  FlightNum         ...         TaxiIn  TaxiOut  \
2         849            PS       1451         ...            NaN      NaN   
3         849            PS       1451         ...            NaN      NaN   
4         849            PS       1451         ...            NaN      NaN   

   Cancelled  CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
2          0               NaN         0           NaN          NaN      NaN   
3          0               NaN         0           NaN          NaN      NaN   
4          0               NaN         0           NaN          NaN      NaN   

   SecurityDelay  LateAircraftDelay   
2            NaN                 NA   
3            NaN                 NA   
4            NaN                 NA   

[3 rows x 29 columns]

In [133]:
dataframe.Year.iloc[5:10].describe()

count       5.0
mean     1987.0
std         0.0
min      1987.0
25%      1987.0
50%      1987.0
75%      1987.0
max      1987.0
Name: Year, dtype: float64

In [146]:
dataframe.Year.where(dataframe.Year>1990,dataframe.Year+10)

0     1997
1     1997
2     1997
3     1997
4     1997
5     1997
6     1997
7     1997
8     1997
9     1997
10    1997
11    1997
12    1997
13    1997
14    1997
15    1997
16    1997
17    1997
18    1997
19    1997
20    1997
21    1997
22    1997
23    1997
24    2008
25    2008
26    2008
27    2008
28    2008
29    2008
30    2008
31    2008
32    2008
33    2008
34    2008
35    2008
36    2008
37    2008
38    2008
39    2008
40    2008
41    2008
42    2008
43    2008
44    2008
45    2008
46    2008
47    2008
48    2008
49    2008
Name: Year, dtype: int64

In [143]:
dataframe[(dataframe.Year>=1987) & (dataframe.Year<=2000)]

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0   1987     10          14          3      741         730      912   
1   1987     10          15          4      729         730      903   
2   1987     10          17          6      741         730      918   
3   1987     10          18          7      729         730      847   
4   1987     10          19          1      749         730      922   
5   1987     10          21          3      728         730      848   
6   1987     10          22          4      728         730      852   
7   1987     10          23          5      731         730      902   
8   1987     10          24          6      744         730      908   
9   1987     10          25          7      729         730      851   
10  1987     10          26          1      735         730      904   
11  1987     10          28          3      741         725      919   
12  1987     10          29          4      742         725      906   
13  1987     10          31          6      726         725      848   
14  1987     10           1          4      936         915     1035   
15  1987     10           2          5      918         915     1017   
16  1987     10           3          6      928         915     1037   
17  1987     10           4          7      914         915     1003   
18  1987     10           5          1     1042         915     1129   
19  1987     10           6          2      934         915     1024   
20  1987     10           7          3      946         915     1037   
21  1987     10           8          4      932         915     1033   
22  1987     10           9          5      947         915     1036   
23  1987     10          10          6      915         915     1022   

    CRSArrTime UniqueCarrier  FlightNum         ...         TaxiIn  TaxiOut  \
0          849            PS       1451         ...            NaN      NaN   
1          849            PS       1451         ...            NaN      NaN   
2          849            PS       1451         ...            NaN      NaN   
3          849            PS       1451         ...            NaN      NaN   
4          849            PS       1451         ...            NaN      NaN   
5          849            PS       1451         ...            NaN      NaN   
6          849            PS       1451         ...            NaN      NaN   
7          849            PS       1451         ...            NaN      NaN   
8          849            PS       1451         ...            NaN      NaN   
9          849            PS       1451         ...            NaN      NaN   
10         849            PS       1451         ...            NaN      NaN   
11         855            PS       1451         ...            NaN      NaN   
12         855            PS       1451         ...            NaN      NaN   
13         855            PS       1451         ...            NaN      NaN   
14        1001            PS       1451         ...            NaN      NaN   
15        1001            PS       1451         ...            NaN      NaN   
16        1001            PS       1451         ...            NaN      NaN   
17        1001            PS       1451         ...            NaN      NaN   
18        1001            PS       1451         ...            NaN      NaN   
19        1001            PS       1451         ...            NaN      NaN   
20        1001            PS       1451         ...            NaN      NaN   
21        1001            PS       1451         ...            NaN      NaN   
22        1001            PS       1451         ...            NaN      NaN   
23        1001            PS       1451         ...            NaN      NaN   

    Cancelled  CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0           0               NaN         0           NaN          NaN      NaN   
1           0               NaN         0           NaN          